export default {

  docker: {
    name: 'Docker',
    dockerFile: {
      fileName: 'Dockerfile',
      fileContents: '# Use the official Node runtime as a parent image\n' +
      '# More info at https://hub.docker.com/_/node/\n' +
      'FROM node:alpine\n' +
      '    \n' +
      '# Set the working directory\n' +
      'WORKDIR /usr/src/app\n' +
      '\n' +
      '# Install app dependencies\n' +
      'COPY package.json package-lock.json ./\n' +
      'RUN npm install\n' +
      '\n' +
      '# Bundle app source\n' +
      'COPY . .\n' +
      '\n' +
      '# Make port 8080 available to the world outside this container\n' +
      'EXPOSE 8080\n' +
      '\n' +
      '# Run "npm start" when the container launches\n' +
      'CMD ["npm", "start"]\n',
      error: {
        fileWrite: 'Failed to write Dockerfile!'
      }
    },

    dockerIgnore: {
      fileName: '.dockerignore',
      fileContents: 'node_modules\n' +
      'npm-debug.log',
      error: {
        fileWrite: 'Failed to write .dockerignore!'
      }
    }
  },

  git: {
    name: 'Git',
    gitIgnore: {
      fileName: '.gitignore',
      fileContents: '### Node ###\n' +
      '# Logs\n' +
      'logs\n' +
      '*.log\n' +
      'npm-debug.log*\n' +
      'yarn-debug.log*\n' +
      'yarn-error.log*\n' +
      '\n' +
      '# Runtime data\n' +
      'pids\n' +
      '*.pid\n' +
      '*.seed\n' +
      '*.pid.lock\n' +
      '\n' +
      '# Directory for instrumented libs generated by jscoverage/JSCover\n' +
      'lib-cov\n' +
      '\n' +
      '# Coverage directory used by tools like istanbul\n' +
      'coverage\n' +
      '\n' +
      '# nyc test coverage\n' +
      '.nyc_output\n' +
      '\n' +
      '# Grunt intermediate storage (http://gruntjs.com/creating-plugins#storing-task-files)\n' +
      '.grunt\n' +
      '\n' +
      '# Bower dependency directory (https://bower.io/)\n' +
      'bower_components\n' +
      '\n' +
      '# node-waf configuration\n' +
      '.lock-wscript\n' +
      '\n' +
      '# Compiled binary addons (http://nodejs.org/api/addons.html)\n' +
      'build/Release\n' +
      '\n' +
      '# Dependency directories\n' +
      'node_modules/\n' +
      'jspm_packages/\n' +
      '\n' +
      '# Typescript v1 declaration files\n' +
      'typings/\n' +
      '\n' +
      '# Optional npm cache directory\n' +
      '.npm\n' +
      '\n' +
      '# Optional eslint cache\n' +
      '.eslintcache\n' +
      '\n' +
      '# Optional REPL history\n' +
      '.node_repl_history\n' +
      '\n' +
      '# Output of \'npm pack\'\n' +
      '*.tgz\n' +
      '\n' +
      '# Yarn Integrity file\n' +
      '.yarn-integrity\n' +
      '\n' +
      '# dotenv environment variables file\n' +
      '.env',
      error: {
        fileWrite: 'Failed to write .gitignore!'
      }
    }
  },

  travisCI: {
    name: 'TravisCI',
    fileName: '.travis.yml',
    fileContents: '' +
    'language: node_js\n' +
    'node_js:\n' +
    '  - \'5\'\n' +
    '\n' +
    'notifications:\n' +
    '  email:\n' +
    '    on_success: never',
    error: {
      fileWrite: 'Failed to write .travis.yml!',
      enableTravisOnProject: 'Failed to enable TravisCI for the project!'
    }
  },

  github: {
    username: {
      name: 'githubUsername',
      message: 'GitHub Username:'
    },

    password: {
      name: 'githubPassword',
      message: 'GitHub Password:'
    }
  },

  dockerHub: {
    username: {
      name: 'dockerHubUsername',
      message: 'Docker Hub Username:'
    },

    password: {
      name: 'dockerHubPassword',
      message: 'Docker Hub Password:'
    }
  },

  hammer: {
    name: 'hammer-io',
    cliName: 'hammer-cli'
  },

  indexJS: {
    fileName: 'index.js',
    fileContents: '\n' +
    'function main() {\n' +
    '  console.log(\'Hello World\');\n' +
    '}\n' +
    '\n' +
    'main();\n',
    error: {
      fileWrite: 'Failed to write index.js!',
      fileRead: 'Failed to read template-index.js!'
    }
  },

  config: {
    projectName: {
      name: 'projectName',
      message: 'Project Name:',

      error: {
        invalidMessage: 'Invalid Project Name!',
        duplicateMessage: 'Project with this name already exists in this directory!'
      }
    },

    description: {
      name: 'description',
      message: 'Description:'
    },

    version: {
      name: 'version',
      message: 'Version:',

      error: {
        invalidMessage: 'Invalid Version Number!'
      }
    },

    author: {
      name: 'author',
      message: 'Author:'
    },

    license: {
      name: 'license',
      message: 'License:',

      error: {
        invalidMessage: 'Invalid License!'
      }
    },

    ci: {
      name: 'ci',
      message: 'Choose your CI tool:'
    },

    container: {
      name: 'container',
      message: 'Choose your containerization tool:'
    }
  }
}
